setup:
        project: test-project
        entity: ai-dtu
        experiment: "batch_size"
log:
        loss: true
        img: true
        n_images: 4
        frequency: 1
        FID: false
        epoch_frequency: 1
        parameters: false