setup:
        project: test-project
        entity: ai-dtu
        experiment: "model_size"
log:
        loss: true
        img: false
        n_images: 10
        frequency: 1000
        FID: false
        epoch_frequency: 1
        parameters: false