setup:
        project: test-project
        entity: ai-dtu
        experiment: "model_size" # train #"batch_size"
log:
        loss: true
        img: true
        n_images: 10
        frequency: 1
        FID: false
        epoch_frequency: 1
        parameters: true