setup:
        project: test-project
        entity: ai-dtu
        experiment: "model_size" # train #"batch_size"
log:
        loss: true
        img: false
        n_images: 10
        frequency: 1
        FID: false
        epoch_frequency: 1
        parameters: true

# 
#art = wandb.Artifact("my-object-detector", type="model")
#art.add_file("saved_model_weights.pt")
#wandb.log_artifact(art)