setup:
        project: test-project
        entity: ai-dtu
log:
        loss: true
        img: False
        n_images: 10
        frequency: 1000
        FID: false
        epoch_frequency: 1
        parameters: false