name: ddpm_unet
#type: independent_func
#size: big
type: classifier # classifier # score
key: 42
sharding: True
guidance: False
hyperparameters: 
  momentum: 0.99
  eps: 0.00001
  dropout_p: 0.1
  upsampling_factor: 2
  downsampling_factor: 2
  time_embedding_dims: 256
  time_embedding_inner_dim: 128
  text_embedding_dims: 256
  anti_blowup_factor: 0.01
  kernel_size: 3
  avg_length: 200
  scaling_factors:
    - 2
    - 2
    - 2
    - 1
parameters:
  Channel_sizes:
    - 128
    - 256
    - 256
    - 256
