name: ddpm_unet
type: independent_func
size: big
key: 42
sharding: False
hyperparameters: 
  momentum: 0.99
  eps: 0.00001
  dropout_p: 0.0
  upsampling_factor: 2
  downsampling_factor: 2
  time_embedding_dims: 784
  time_embedding_inner_dim: 128
  text_embedding_dims: 784
  inference: False
  anti_blowup_factor: 0.01
  kernel_size: 3
  avg_length: 200
parameters:
  Channel_sizes:
    - 128
    - 256
    - 256
    - 256