name: ddpm_unet
type: independent_func
size: big
key: 4269
sharding: True
hyperparameters: 
  momentum: 0.99
  eps: 0.00001
  dropout_p: 0.1
  upsampling_factor: 2
  downsampling_factor: 2
  time_embedding_dims: 128
  inference: False
  anti_blowup_factor: 0.03
  kernel_size: 3
  avg_length: 200
parameters:
  Channel_sizes:
    - 4
    - 4
    - 4
    - 4