mode: train # validation, train
train:
   batch_size: 12
   epochs: 1000
   shuffle: true
test:
   batch_size: 10
   split_factor: 200
   shuffle: false
   img_save_loc: "gen_imgs/"
   fid_features: 64 # 64, 192, 768, 2048
   fid_model_type: tensorflow
   text_classifier: "CLIP-ViT-H-14"