defaults:
        - wandb : defaults # results
        - dataset: mnist # cifar10 # mnist
        - train_and_test: default
        - model : ddpm_simple #ddpm_simple # dummy 
        - visualization: local_visualization
        - optimizer: adam
        - sde: paper_subvp
        - loss: cross_entropy # yangsong # combined_sm #denoise_sm #implicit_sm #none
        - time: time
        - parameter_loading: default
        - text_embedding: vith14
