defaults:
        - wandb : defaults
        - dataset: cifar10
        - train_and_test: default
        - model : ddpm_unet_mega_downscaled
        - visualization: visualize
        - optimizer: gradient_descent
        - sde: paper_subvp
        - loss: implicit_sm