defaults:
        - wandb : defaults
        - dataset: cifar10
        - train_and_test: default
        - model : dummy_giant #dummy #ddpm_unet_mega_downscaled # dummy_giant # dummy 
        - visualization: visualize
        - optimizer: adam
        - sde: paper_subvp
        - loss: implicit_sm #denoise_sm #implicit_sm