defaults:
        - wandb : defaults
        - dataset: cifar10
        - train_and_test: default
        - model : sde #ddpm_simple # dummy #dummy #ddpm_unet_mega_downscaled # dummy_giant # dummy 
        - visualization: local_visualization
        - optimizer: adam
        - sde: paper_subvp
        - loss: implicit_sm #denoise_sm #implicit_sm #none
        - time: time