defaults:
        - wandb : defaults
        - dataset: mnist
        - train_and_test: default
        - model : dummy #ddpm_simple # dummy #dummy #ddpm_unet_mega_downscaled # dummy_giant # dummy 
        - visualization: local_visualization
        - optimizer: adam
        - sde: paper_subvp
        - loss: combined_sm # yangsong # combined_sm #denoise_sm #implicit_sm #none
        - time: time
        - parameter_loading: default
        - text_embedding: vith14
